In [1]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
} 

df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [2]:
df["Promoted Salary"] = df["Salary"] * 10

In [3]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

###

# Data Cleaning

## 1.   Checking count of Null Values in df

In [4]:
df.isnull().sum()

Name               0
Age                1
Department         0
Salary             1
Promoted Salary    1
dtype: int64

###

## 2.  To remove rows which have null values

In [5]:
df.dropna()

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
5    Alice  25.0         HR  50000.0         500000.0

### Parameters of dropna()    --> How want our null values will be deletetd or drop

### A. how = "any"   (default)

In [6]:
df.dropna(how = "any")  # any row that had any null value

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
5    Alice  25.0         HR  50000.0         500000.0

### B. how = "all"

In [7]:
df.dropna(how = "all") # If all the values in any row are null then we drop otherwise we do not touch it

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

In [12]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

###

## 3. Fill the missing values

### A. Fill by some universal value like 0

In [13]:
 df.fillna(0)  # This is noob method because we don't want the Salary and Age from nulll to 0 because that is not fair value

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   0.0         IT  62000.0         620000.0
4      Eve  29.0         HR      0.0              0.0
5    Alice  25.0         HR  50000.0         500000.0

### B. Replace by mean

In [15]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [16]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

### C. Replace by Median

In [17]:
df["Salary"].fillna(df["Salary"].median())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    60000.0
5    50000.0
Name: Salary, dtype: float64

### D. Replace by Forward Fill --> Means the missing value's above value is present then it will be set as new value insted of missing value

Error Case : If the first value is NULL and you try to forward fill then it will be still NULL after performing forward fill
Solution : Replace missing value by mean or median or mode

In [20]:
# df["Age"].fillna(method="ffill")  # --> Not working syntax
df["Age"].ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

### E. Replace by Backward Fill --> Means the missing value's below value is present then it will be set as new value insted of missing value

Error Case : If the last value is NULL and you try to backward fill then it will be still NULL after performing backward fill
Solution : Replace missing value by mean or median or mode

In [21]:
df["Age"].bfill()

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

###

###

## 4. Replacing the Current value with new Value

In [23]:
# Replacing Charlie Name with Rose in the Name column
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: str

In [24]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

In [25]:
# If want this change parmenantly 
df["Name"] = df["Name"].replace("Charlie","Rose")

In [26]:
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0
1    Bob  30.0         IT  60000.0         600000.0
2   Rose  35.0    Finance  70000.0         700000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  29.0         HR      NaN              NaN
5  Alice  25.0         HR  50000.0         500000.0

###

## 5. Handling of duplicate value

### A. Identifying Duplicate Values

In [27]:
df_dup = df[df.duplicated()]
df_dup

    Name   Age Department   Salary  Promoted Salary
5  Alice  25.0         HR  50000.0         500000.0

###

### Woking of Duplicate checking

s = [Italy, France, Rome, Italy]  --> Start from initial and add unique values into another array if same element agian show then just mark it as duplicated

###

#### Parameters of duplicated()

#### I. keeps = "first" --> By default  --> This means mark other values except first as duplicated

In [28]:
df_dup = df[df.duplicated(keep="first")]
df_dup

    Name   Age Department   Salary  Promoted Salary
5  Alice  25.0         HR  50000.0         500000.0

#### II. keeps = "last"  --> This means mark other values except last as duplicated

In [29]:
df_dup = df[df.duplicated(keep="last")]
df_dup

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0

###

### B. Drop Duplicated value

In [42]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
} 

df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [43]:
df = df.drop_duplicates()

In [44]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN