In [1]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
} 

df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

###

In [2]:
df["Promoted Salary"] = df["Salary"] * 10

In [3]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0         500000.0

###

# Dealing with Invalid Values

## A. Lambda Function

--> To perform task on the particular column and it is like list comprehension means doing all the task in one line command

In [11]:
# Just want to reduce the salary by 10th part whose salary is greater than 60,000 From Promoted Salary
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>60000 else x)

In [12]:
df

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0          50000.0
1      Bob  30.0         IT  60000.0          60000.0
2  Charlie  35.0    Finance  70000.0           7000.0
3    David   NaN         IT  62000.0           6200.0
4      Eve  29.0         HR      NaN              NaN
5    Alice  25.0         HR  50000.0          50000.0

###

## B.  Split the Values

In [14]:
df["Name"] = df["Name"].replace("Alice","Alice_Fernandes")

In [15]:
df

              Name   Age Department   Salary  Promoted Salary
0  Alice_Fernandes  25.0         HR  50000.0          50000.0
1              Bob  30.0         IT  60000.0          60000.0
2          Charlie  35.0    Finance  70000.0           7000.0
3            David   NaN         IT  62000.0           6200.0
4              Eve  29.0         HR      NaN              NaN
5  Alice_Fernandes  25.0         HR  50000.0          50000.0

In [16]:
df[["First_Name","Last_Name"]] = df["Name"].str.split("_")

ValueError: Columns must be same length as key

Error because of Other name has not _ pattern in their Full name and here just given single word name only

###

## C. apply() usage

In [20]:
# Suppose we need to multiply all person's age by 2 but without using lambda function then..
def multiplying_by_two(x):
    return x*2

df["Age"] = df["Age"].apply(multiplying_by_two)

Here we not pass any input and pandas is smart enough to understand that it need to take one by one element from given column..

In [21]:
df

              Name   Age Department   Salary  Promoted Salary
0  Alice_Fernandes  50.0         HR  50000.0          50000.0
1              Bob  60.0         IT  60000.0          60000.0
2          Charlie  70.0    Finance  70000.0           7000.0
3            David   NaN         IT  62000.0           6200.0
4              Eve  58.0         HR      NaN              NaN
5  Alice_Fernandes  50.0         HR  50000.0          50000.0

###

In [22]:
# Suppose we need to divide the age by 2 then..
df["Age"] = df["Age"].apply(lambda x:x/2)

In [23]:
df

              Name   Age Department   Salary  Promoted Salary
0  Alice_Fernandes  25.0         HR  50000.0          50000.0
1              Bob  30.0         IT  60000.0          60000.0
2          Charlie  35.0    Finance  70000.0           7000.0
3            David   NaN         IT  62000.0           6200.0
4              Eve  29.0         HR      NaN              NaN
5  Alice_Fernandes  25.0         HR  50000.0          50000.0

###

###

# Joints and Merges

Suppose there are two excel files of House related data in which
1. The Inside data of the House like No. of Bedrooms, No. of Bathrooms, etc..
2. The Outer data of the HOuse like Location, Price, etc...
Now, if we need to combine this two excel files and want to get full House Details for the Better understanding of data and also for the better prediction process so at that time we use the joints and merges

Join  -> left(Only A), right(Only B), inner(A Intersection B), outer(A Union B), cross
Merge -> use intersection and also can see the property of the A and B

In [24]:
department_info = {
    "Department": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame (department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

###

## A. concat()

To Perform the merge operation we use the function concat()

In [25]:
pd.concat([df,df2])

,Name,Age,Department,Salary,Promoted Salary,Location,Manager
0,Alice_Fernandes,25.0,HR,50000.0,50000.0,NaN,NaN
1,Bob,30.0,IT,60000.0,60000.0,NaN,NaN
2,Charlie,35.0,Finance,70000.0,7000.0,NaN,NaN
3,David,NaN,IT,62000.0,6200.0,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN
5,Alice_Fernandes,25.0,HR,50000.0,50000.0,NaN,NaN
0,NaN,NaN,HR,NaN,NaN,New York,Laura
1,NaN,NaN,IT,NaN,NaN,San Francisco,Steve
2,NaN,NaN,Finance,NaN,NaN,Chicago,Nina

by this simply horizontal concatination is done and in this Whatever value is known that will filled and whichever we do not know that is filled by NaN like the Name and age of df2 and Location and Manager of df1

In [26]:
# To make this perfectly we can also do the vertical concatination also

In [27]:
pd.concat([df,df2], axis=1)

,Name,Age,Department,Salary,Promoted Salary,Department,Location,Manager
0,Alice_Fernandes,25.0,HR,50000.0,50000.0,HR,New York,Laura
1,Bob,30.0,IT,60000.0,60000.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,70000.0,7000.0,Finance,Chicago,Nina
3,David,NaN,IT,62000.0,6200.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
5,Alice_Fernandes,25.0,HR,50000.0,50000.0,NaN,NaN,NaN

###

## B. merge()

In [28]:
# Here in above output there is Department column is repeats twice and we do not want it and so for it...

In [32]:
pd.merge(df,df2, on="Department")

,Name,Age,Department,Salary,Promoted Salary,Location,Manager
0,Alice_Fernandes,25.0,HR,50000.0,50000.0,New York,Laura
1,Bob,30.0,IT,60000.0,60000.0,San Francisco,Steve
2,Charlie,35.0,Finance,70000.0,7000.0,Chicago,Nina
3,David,NaN,IT,62000.0,6200.0,San Francisco,Steve
4,Eve,29.0,HR,NaN,NaN,New York,Laura
5,Alice_Fernandes,25.0,HR,50000.0,50000.0,New York,Laura

###

merge() and join() syntax is basically same

## C. join()