# DataFrame

In [6]:
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [7]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [9]:
import pandas as pd
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

###

### To show dataframe

In [10]:
# To show first n rows 
df.head(2)   # By default value is 5 like df.head() --> will show you first 5 rows

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [11]:
# To show last n rows
df.tail(3)   # By default value is 5 like df.tail() --> will show you last 5 rows

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

###

###  iloc and loc

In [12]:
# To show 1st and 2nd row only 
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [13]:
# Suppose want 1st and 2nd row with Age and Department column only then...
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [14]:
df.loc[1:3,["Age":"Salary"]]    # This experiment gives an error

SyntaxError: invalid syntax (654640405.py, line 1)

In [17]:
# To want this columns use column number with 'iloc' like
df.iloc[1:3, 1:4]    # range(rows), range(columns)  --> here end no of row is included but end no of column is excluded.

    Age Department   Salary
1  30.0         IT  60000.0
2  35.0    Finance  70000.0

###

### To show perticular column of the dataframe

In [18]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [19]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [20]:
s = pd.Series(df["Age"])  # Experiment and usage of the Accessing perticular column and declare as series

In [21]:
s

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

###

### Drop Particular Column from the dataframe

In [22]:
df.drop("Age", axis=1)   # We can show that at this moment 'Age' column in gone but...

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

axis = 1 indicates entire column will gone
axis = 0 indicates entire row will gone

In [23]:
df   # Here We can show the 'Age' Column

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

So, If we wish to Remove the 'Age' Column permanently from the df then set parameter "inplace = True" 
--> By default it is False.

In [24]:
df.drop("Age", axis=1, inplace=True)

In [25]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

###

### Check Information of the Dataframe

In [26]:
df.shape

(6, 3)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      5 non-null      float64
dtypes: float64(1), str(2)
memory usage: 276.0 bytes

In [29]:
df.describe() # Provide statistical information of the numeric column of the dataframe

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

###

### Broadcasting

In [32]:
df["Salary"]

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64

In [34]:
# Suppose want to increase the salary of each person by 5000
df["Salary"] += 5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [35]:
df # We can see that the changes are also affects in the original dataframe also thus why this is mutable datastructure

      Name Department   Salary
0    Alice         HR  55000.0
1      Bob         IT  65000.0
2  Charlie    Finance  75000.0
3    David         IT  67000.0
4      Eve         HR      NaN
5    Alice         HR  55000.0

###

### Renaming the Columns

In [37]:
df.rename(columns = {"Department":"Dept"}, inplace = True)
df

      Name     Dept   Salary
0    Alice       HR  55000.0
1      Bob       IT  65000.0
2  Charlie  Finance  75000.0
3    David       IT  67000.0
4      Eve       HR      NaN
5    Alice       HR  55000.0

###

### Check unique Values in df

In [38]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

###

### value_counts()

Suppose want to find the How many times unique values are repeated then for it value_counts() is used

In [40]:
df

      Name     Dept   Salary
0    Alice       HR  55000.0
1      Bob       IT  65000.0
2  Charlie  Finance  75000.0
3    David       IT  67000.0
4      Eve       HR      NaN
5    Alice       HR  55000.0

In [42]:
df["Dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [39]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

###

### To add new column in the df

In [45]:
# If we want to add Promoted Salary column which is 10 times of salary column of the all promoted employee
df["Promoted Salary"] = df["Salary"] * 10
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  55000.0         550000.0